version: "1"
# Valid no-op configuration for Pull app.
# This rule compares main..main within the same repo and never produces changes.
rules:
  - base: main
    upstream: main
    mergeMethod: none
label: ":no_entry: pull disabled"
conflictLabel: "pull-disabled"
